name: "RedSock/Distribute"
description: "Copies source code to another git system"

author: "RedSock"

branding:
  icon: "shuffle"
  color: "red"

inputs:
  TARGET_REPOS:
    description: "Coma separated different origin urls with auth"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}

    - name: Distribute
      shell: bash
      env:
        REPOS: ${{ inputs.TARGET_REPOS }}
      run: |
        IFS=';' read -ra ADDR <<< "$REPOS"
        git fetch --unshallow origin
        for i in "${ADDR[@]}"; do
          git remote remove origin  
          git remote add origin "$i"
          git push --set-upstream origin --all
          git push --set-upstream origin --tags
        done
