name: "RedSock/Distribute"
description: "Copies source code to another git system"

author: "RedSock"

branding:
  icon: "shuffle"
  color: "red"

inputs:
  target_repos:
    description: "Coma separated different origin urls with auth"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}

    - name: Dependencies
      shell: bash
      run: |
        pip install GitPython

    - name: Distribute
      shell: python
      env:
        REPOS: ${{ inputs.target_repos }}
        KEYS: ${{ inputs.target_repos_keys-repos }}
      run: |
        import git
        import os
        
        repos_urls = os.environ['REPOS'].split(',')
        
        repo = git.Repo('./')
              
        for idx, _ in enumerate(repos_urls):
          remote_name = str(idx)
          if repo.remotes.__contains__(remote_name):
            try:
              repo.delete_remote(git.Remote(repo, remote_name))
            except git.exc.GitCommandError:
              pass
          repo.create_remote(remote_name, repos_urls[idx])
          repo.remote(remote_name).push()
