name: "RedSock/Distribute"
description: "Copies source code to another git system"

author: "RedSock"

branding:
  icon: "shuffle"
  color: "red"

inputs:
  target_repos:
    description: "Coma separated different origin urls"
    required: true
  netrc:
    description: "Login info in netrc format"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}

    - name: Dependencies
      shell: bash
      run: |
        pip install GitPython

    - name: Prepare netrc
      shell: bash
      run: |
        touch ~/.netrc
        echo ${{ inputs.netrc }} >> ~/.netrc
    - name: Distribute
      shell: python
      env:
        REPOS: ${{ inputs.target_repos }}
        KEYS: ${{ inputs.target_repos_keys-repos }}
      run: |
        import git
        import os
        
        repos_urls = os.environ['REPOS'].split(',')
        
        repo = git.Repo('./')
      
        for rep in repos_urls:
          remote_name = rep.replace("/", "_").replace("https:__", "")
          if repo.remotes.__contains__(remote_name):
            try:
              repo.delete_remote(git.Remote(repo, remote_name))
            except git.exc.GitCommandError:
              pass
          repo.create_remote(remote_name, rep)
          repo.remote(remote_name).push()
